CREATE TABLE Axp__AppMgrMS1
(
  Axp__AppMgrMS1ID       INTEGER,
  CANCEL         CHAR(1 BYTE),
  SOURCEID       INTEGER,
  MAPNAME        VARCHAR2(20 BYTE),
  USERNAME       VARCHAR2(50 BYTE),
  MODIFIEDON     DATE,
  CREATEDBY      VARCHAR2(50 BYTE),
  CREATEDON      DATE,
  WKID           VARCHAR2(15 BYTE),
  APP_LEVEL      NUMBER(3),
  APP_DESC       NUMBER(1),
  APP_SLEVEL     NUMBER(3),
  CANCELREMARKS  VARCHAR2(150 BYTE),
  WFROLES        VARCHAR2(250 BYTE)
)