<<
CREATE TABLE AX_LAYOUTDESIGN(
    DESIGN_ID NUMBER(10,0) primary key,
    TRANSID VARCHAR2(255),
    MODULE VARCHAR2(255),
    CONTENT NCLOB,
    CREATED_BY VARCHAR2(255),
    UPDATED_BY VARCHAR2(255),
    IS_DELETED VARCHAR2(1) DEFAULT 'N',
    IS_PRIVATE VARCHAR2(1) DEFAULT 'N',
    CREATED_ON TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
    IS_MIGRATED VARCHAR2(1) DEFAULT 'N'
)
>>
<<
CREATE SEQUENCE ax_layoutdesign_seq START WITH 1
>>
<<
CREATE OR REPLACE TRIGGER AX_LAYOUTDESIGN_bir 
BEFORE INSERT ON AX_LAYOUTDESIGN FOR EACH ROW 
BEGIN 
    :new.DESIGN_ID := ax_layoutdesign_seq.nextval; 
END;
>>
<<
CREATE TABLE AX_LAYOUTDESIGN_SAVED(
    DESIGN_ID NUMBER(10,0) primary key,
    TRANSID VARCHAR2(255),
    MODULE VARCHAR2(255),
    CONTENT NCLOB,
    CREATED_BY VARCHAR2(255),
    UPDATED_BY VARCHAR2(255),
    IS_DELETED VARCHAR2(1) DEFAULT 'N',
    CREATED_ON TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
    IS_MIGRATED VARCHAR2(1) DEFAULT 'N',
    IS_PUBLISH VARCHAR2(1) DEFAULT 'N',
    IS_PRIVATE VARCHAR2(1) DEFAULT 'N',
    PARENT_DESIGN_ID NUMBER(10,0),
    RESPONSIBILITY NCLOB,
    ORDER_BY NUMBER
)
>>
<<
CREATE SEQUENCE ax_layoutdesign_saved_seq START WITH 1
>>
<<
CREATE OR REPLACE TRIGGER AX_LAYOUTDESIGN_SAVED_bir 
BEFORE INSERT ON AX_LAYOUTDESIGN_SAVED FOR EACH ROW 
BEGIN 
    :new.DESIGN_ID := ax_layoutdesign_saved_seq.nextval; 
END;
>>
