CREATE TABLE Axp__AppMgrMS1
(
  Axp__AppMgrMS1ID       NUMERIC,
  CANCEL         CHAR(1),
  SOURCEID       INTEGER,
  MAPNAME        VARCHAR(20),
  USERNAME       VARCHAR(50),
  MODIFIEDON     DATETIME,
  CREATEDBY      VARCHAR(50),
  CREATEDON      DATETIME,
  WKID           VARCHAR(15),
  APP_LEVEL      NUMERIC(3),
  APP_DESC       NUMERIC(1),
  APP_SLEVEL     NUMERIC(3),
  CANCELREMARKS  VARCHAR(150),
  WFROLES        VARCHAR(250)
)